# Dnero mainnet wallet node configuration
storage:
  statePruningRetainedBlocks: 2048
p2p:
  opt: 0
  port: 41000
  seeds: 45.76.65.243:41000,155.138.227.130:41000,140.82.62.22:41000
  minNumPeers: 24
  maxNumPeers: 96
  natMapping: true
rpc:
  port: 15511
  enabled: true
  address: 127.0.0.1
log:
  levels: "*:info,guardian:debug"