# Dnero mainnet wallet node configuration
storage:
  statePruningRetainedBlocks: 2048
p2p:
  opt: 0
  port: 21100
  #seeds: IP:PORT,IP:PORT,IP:PORT
  minNumPeers: 24
  maxNumPeers: 96
  natMapping: true
rpc:
  port: 14411
  enabled: true
  address: 127.0.0.1
log:
  levels: "*:info,guardian:debug"