# Dnero testchainnet wallet node configuration
storage:
  statePruningRetainedBlocks: 2048
p2p:
  opt: 0
  port: 31000
  seeds: 208.68.38.10:31000,45.77.71.222:31000,45.76.249.125:31000,149.28.194.235:31000
  minNumPeers: 24
  maxNumPeers: 96
  natMapping: true
rpc:
  port: 15511
  enabled: true
  address: 127.0.0.1
log:
  levels: "*:info,guardian:debug"