# Dnero mainnet wallet node configuration
storage:
  statePruningRetainedBlocks: 2048
p2p:
  opt: 0
  port: 31000
  seeds: 45.76.65.243:31000,155.138.227.130:31000,140.82.62.22:31000
  minNumPeers: 24
  maxNumPeers: 96
  natMapping: true
rpc:
  port: 15511
  enabled: true
  address: 127.0.0.1
log:
  levels: "*:info,guardian:debug"